GET http://localhost:3001/api/persons/
### 
GET http://localhost:3001/info 
###
DELETE http://localhost:3001/api/persons/
### 
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
"name": "HieuNguyen", "number": "901-2333123"
}